import type { UsuarioLeer } from './types'

// Datos de prueba para CA-01 mientras el backend de HU-03 no tiene migración
// (ver hallazgos de la revisión de origin/feature/HU03-CRUD-de-usuarios).
export const USUARIOS_MOCK: UsuarioLeer[] = [
  {
    id: 1,
    correo: 'admin.ori@usbcali.edu.co',
    nombre_completo: 'Laura Fernanda Ríos',
    documento_identidad: '1107654321',
    telefono: '3001234567',
    cargo: 'Coordinadora ORI',
    rol: { codigo: 'ADMINISTRADOR_ORI', nombre: 'Administrador ORI' },
    activo: true,
    ultimo_acceso: '2026-09-15T14:20:00Z',
  },
  {
    id: 2,
    correo: 'jesus.gelves@usbcali.edu.co',
    nombre_completo: 'Jesús Gelves',
    documento_identidad: '1044556677',
    telefono: '3012345678',
    cargo: 'Desarrollador backend',
    rol: { codigo: 'GESTOR_ORI', nombre: 'Gestor ORI' },
    activo: true,
    ultimo_acceso: '2026-09-16T09:05:00Z',
  },
  {
    id: 3,
    correo: 'ian.arango@usbcali.edu.co',
    nombre_completo: 'Ian Marco Arango',
    documento_identidad: '1098765432',
    telefono: '3023456789',
    cargo: 'Desarrollador frontend',
    rol: { codigo: 'REVISOR_ORI', nombre: 'Revisor ORI' },
    activo: true,
    ultimo_acceso: null,
  },
  {
    id: 4,
    correo: 'juan.palacio@usbcali.edu.co',
    nombre_completo: 'Juan D. Palacio Obregón',
    documento_identidad: '1055443322',
    telefono: null,
    cargo: 'Desarrollador backend',
    rol: { codigo: 'GESTOR_ORI', nombre: 'Gestor ORI' },
    activo: true,
    ultimo_acceso: '2026-09-14T16:40:00Z',
  },
  {
    id: 5,
    correo: 'revisor.suplente@usbcali.edu.co',
    nombre_completo: 'Camila Torres',
    documento_identidad: '1077889900',
    telefono: '3034567890',
    cargo: 'Revisora jurídica',
    rol: { codigo: 'REVISOR_ORI', nombre: 'Revisor ORI' },
    activo: false,
    ultimo_acceso: '2026-08-30T11:15:00Z',
  },
  {
    id: 6,
    correo: 'admin.suplente@usbcali.edu.co',
    nombre_completo: 'Andrés Valencia',
    documento_identidad: null,
    telefono: null,
    cargo: null,
    rol: { codigo: 'ADMINISTRADOR_ORI', nombre: 'Administrador ORI' },
    activo: false,
    ultimo_acceso: '2026-07-10T08:00:00Z',
  },
]
