from enum import StrEnum


class TipoAliado(StrEnum):
    UNIVERSIDAD = "UNIVERSIDAD"
    COLEGIO = "COLEGIO"
    EMPRESA = "EMPRESA"
    ENTIDAD_GUBERNAMENTAL = "ENTIDAD_GUBERNAMENTAL"


class TipoIdentificacion(StrEnum):
    NIT = "NIT"
    CEDULA_CIUDADANIA = "CEDULA_CIUDADANIA"
    CEDULA_EXTRANJERIA = "CEDULA_EXTRANJERIA"
    PASAPORTE = "PASAPORTE"
    IDENTIFICACION_FISCAL_EXTRANJERA = "IDENTIFICACION_FISCAL_EXTRANJERA"
    OTRO = "OTRO"


class NaturalezaConvenio(StrEnum):
    MARCO = "MARCO"
    ESPECIFICO = "ESPECIFICO"


class TipoSolicitante(StrEnum):
    INTERNO = "INTERNO"
    EXTERNO = "EXTERNO"


class EstadoSolicitud(StrEnum):
    BORRADOR = "BORRADOR"
    RADICADA = "RADICADA"
    EN_ESTUDIO = "EN_ESTUDIO"
    DEVUELTA = "DEVUELTA"
    APROBADA = "APROBADA"
    RECHAZADA = "RECHAZADA"


class TipoDocumentoSolicitud(StrEnum):
    CAMARA_COMERCIO = "CAMARA_COMERCIO"
    RUT = "RUT"
    CEDULA_REPRESENTANTE_LEGAL = "CEDULA_REPRESENTANTE_LEGAL"
    OTRO_DOCUMENTO_REPRESENTACION = "OTRO_DOCUMENTO_REPRESENTACION"
    OTRO_SOPORTE = "OTRO_SOPORTE"


class EstadoConvenio(StrEnum):
    EN_TRAMITE = "EN_TRAMITE"
    VIGENTE = "VIGENTE"
    POR_VENCER = "POR_VENCER"
    VENCIDO = "VENCIDO"
    RENOVADO = "RENOVADO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"


class AlcanceConvenio(StrEnum):
    PROGRAMA = "PROGRAMA"
    INSTITUCIONAL = "INSTITUCIONAL"


class OrigenObservacionRevision(StrEnum):
    REVISOR_ORI = "REVISOR_ORI"
    CONTRAPARTE = "CONTRAPARTE"
    REVISION_FINAL_ORI = "REVISION_FINAL_ORI"


class EstadoObservacionRevision(StrEnum):
    PENDIENTE = "PENDIENTE"
    ATENDIDA = "ATENDIDA"


class TipoRevisionConvenio(StrEnum):
    JURIDICA = "JURIDICA"
    CONTRAPARTE = "CONTRAPARTE"
    FINAL = "FINAL"


class EstadoRevisionConvenio(StrEnum):
    PENDIENTE = "PENDIENTE"
    RESUELTA = "RESUELTA"


class ResultadoRevisionConvenio(StrEnum):
    APROBADA = "APROBADA"
    DEVUELTA = "DEVUELTA"


class AccionAuditoria(StrEnum):
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    DELETE = "DELETE"


class RolFirmante(StrEnum):
    ADMINISTRADOR_ORI = "ADMINISTRADOR_ORI"
    REVISOR_ORI = "REVISOR_ORI"
    VICERRECTORIA_FINANCIERA = "VICERRECTORIA_FINANCIERA"
    VICERRECTORIA_ACADEMICA = "VICERRECTORIA_ACADEMICA"
    SECRETARIA = "SECRETARIA"
    RECTOR = "RECTOR"
    PARTE_SOLICITANTE = "PARTE_SOLICITANTE"


class ParteFirmante(StrEnum):
    USB = "USB"
    SOLICITANTE = "SOLICITANTE"


class ModalidadFirma(StrEnum):
    ELECTRONICA = "ELECTRONICA"
    FISICA = "FISICA"


class EstadoFirma(StrEnum):
    PENDIENTE = "PENDIENTE"
    FIRMADA = "FIRMADA"
    RECHAZADA = "RECHAZADA"

