"""HU-12 snapshot de revision

Revision ID: 3c946dc86ec5
Revises: d137b5d9ebcf
Create Date: 2026-09-24 02:10:41.228217

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c946dc86ec5'
down_revision: str | Sequence[str] | None = 'd137b5d9ebcf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision_convenio', sa.Column('snapshot_datos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision_convenio', 'snapshot_datos')
    # ### end Alembic commands ###
