"""agregar tablas rol y usuario

Revision ID: 4be1d10a7e04
Revises: 56626120dc9a
Create Date: 2026-09-17 01:38:53.912095

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4be1d10a7e04'
down_revision: str | Sequence[str] | None = '56626120dc9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_interno', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_codigo'), 'rol', ['codigo'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('documento_identidad', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('entidad_externa', sa.String(length=160), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_rol_id'), 'usuario', ['rol_id'], unique=False)

    op.bulk_insert(
        sa.table(
            "rol",
            sa.column("codigo", sa.String),
            sa.column("nombre", sa.String),
            sa.column("descripcion", sa.String),
            sa.column("es_interno", sa.Boolean),
            sa.column("activo", sa.Boolean),
        ),
        [
            {
                "codigo": "ADMINISTRADOR_ORI",
                "nombre": "Administrador ORI",
                "descripcion": "Acceso total. Unico perfil que administra usuarios y roles.",
                "es_interno": True,
                "activo": True,
            },
            {
                "codigo": "GESTOR_ORI",
                "nombre": "Gestor ORI",
                "descripcion": "Gestion operativa de solicitudes y convenios.",
                "es_interno": True,
                "activo": True,
            },
            {
                "codigo": "REVISOR_ORI",
                "nombre": "Revisor ORI",
                "descripcion": "Revision juridica y de validacion institucional.",
                "es_interno": True,
                "activo": True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_rol_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_codigo'), table_name='rol')
    op.drop_table('rol')
    # ### end Alembic commands ###
