"""HU-12 auditoria de cambios

Revision ID: d137b5d9ebcf
Revises: a6c4e2f8b1d9
Create Date: 2026-09-24 01:47:38.007858

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd137b5d9ebcf'
down_revision: str | Sequence[str] | None = 'a6c4e2f8b1d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=80), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("accion IN ('INSERT', 'UPDATE', 'DELETE')", name='ck_auditoria_accion'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_entidad_registro', 'auditoria', ['entidad', 'registro_id'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha_hora'), 'auditoria', ['fecha_hora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_fecha_hora'), table_name='auditoria')
    op.drop_index('ix_auditoria_entidad_registro', table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
