"""agregar entidades pais, aliado, contacto_aliado y convenio minimo

Revision ID: e0823f105930
Revises: 56626120dc9a
Create Date: 2026-09-13 22:16:17.198121

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0823f105930'
down_revision: str | Sequence[str] | None = '56626120dc9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_iso', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('aliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('UNIVERSIDAD', 'COLEGIO', 'EMPRESA', 'ENTIDAD_GUBERNAMENTAL', name='tipo_aliado'), nullable=False),
    sa.Column('sector_economico', sa.String(length=120), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('correo', sa.String(length=160), nullable=True),
    sa.Column('sitio_web', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_aliado'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('contacto_aliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aliado_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('correo', sa.String(length=160), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aliado_id'], ['aliado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aliado_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('EN_TRAMITE', 'VIGENTE', 'POR_VENCER', 'VENCIDO', 'RENOVADO', 'FINALIZADO', 'CANCELADO', name='estado_convenio'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aliado_id'], ['aliado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convenio')
    op.drop_table('contacto_aliado')
    op.drop_table('aliado')
    op.drop_table('pais')
    # ### end Alembic commands ###
    sa.Enum(name='estado_convenio').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='estado_aliado').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tipo_aliado').drop(op.get_bind(), checkfirst=True)
