"""create_firma_convenio_table

Revision ID: f162ef850eec
Revises: a711c4d8e912
Create Date: 2026-09-23 01:21:10.054987

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f162ef850eec'
down_revision: str | Sequence[str] | None = '3c946dc86ec5'

branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma_convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('rol_firmante', sa.String(length=40), nullable=False),
    sa.Column('parte', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_firmante', sa.String(length=160), nullable=True),
    sa.Column('cargo_firmante', sa.String(length=120), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='PENDIENTE', nullable=False),
    sa.Column('fecha_firma', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'FIRMADA', 'RECHAZADA')", name='ck_firma_convenio_estado'),
    sa.CheckConstraint("modalidad IS NULL OR modalidad IN ('ELECTRONICA', 'FISICA')", name='ck_firma_convenio_modalidad'),
    sa.CheckConstraint("parte IN ('USB', 'SOLICITANTE')", name='ck_firma_convenio_parte'),
    sa.CheckConstraint("rol_firmante IN ('ADMINISTRADOR_ORI', 'REVISOR_ORI', 'VICERRECTORIA_FINANCIERA', 'VICERRECTORIA_ACADEMICA', 'SECRETARIA', 'RECTOR', 'PARTE_SOLICITANTE')", name='ck_firma_convenio_rol_firmante'),
    sa.CheckConstraint('orden BETWEEN 1 AND 7', name='ck_firma_convenio_orden_range'),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('convenio_id', 'orden', name='uq_firma_convenio_orden')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firma_convenio')
    # ### end Alembic commands ###
